import { parseDatasourceTypes } from "./parse-datasource-types.ts";
import {
  generateInitialMigration,
  normalizeDialect,
  type SchemaData,
} from "../../lib/generate-sql.ts";
import {
  buildCustomMigrationFiles,
  generateFilesFromPairs,
  type CustomMigrationPair,
} from "./generate-custom-migrations.ts";
import { assertSkipMigrationsCovered } from "./validate-skip-migrations-coverage.ts";
import { resolveSchemaDialects } from "./deterministic-project.ts";
import { chainMigrationEntries } from "./migration-entries.ts";
import { CONTENT } from "./generate-result.ts";
import type { GenerateEntry } from "./generate-result.ts";
import { datasourceSettingsForSettings } from "./ts-datasource-settings.ts";
import {
  structuredSettingsFromDict,
  type SettingsDict,
} from "./settings-dict.ts";

interface CustomMigrationFile {
  filename: string;
  content: string;
}

type IncludedPair = CustomMigrationPair;

interface SqlGenerateInput {
  inputs: {
    dir: string;
    all: () => Promise<{
      datasourceYamlText: string;
      datasourceSeedsYamlText: string | null;
      includedCustomMigrations: Record<string, IncludedPair[]> | undefined;
    }>;
  };
  settings: SettingsDict;
}

// Included custom migrations (carried from a datasource include) are generated alongside the local ones. Two sources landing on the same generated filename — identical (order, name, direction) — is a genuine ambiguity, so throw rather than let one silently win.
function assertNoFilenameClash(
  files: CustomMigrationFile[],
  dialect: string,
): void {
  const seen = new Set<string>();
  for (const file of files) {
    if (seen.has(file.filename)) {
      throw new Error(
        `custom migration filename collision for dialect '${dialect}': ${file.filename} is generated by both an included datasource and this project`,
      );
    }
    seen.add(file.filename);
  }
}

async function customEntries(
  dialect: string,
  deterministicDir: string,
  includedPairs: IncludedPair[] | undefined,
): Promise<GenerateEntry[]> {
  const files: CustomMigrationFile[] = [
    ...generateFilesFromPairs(includedPairs ?? []),
    ...(await buildCustomMigrationFiles(deterministicDir, dialect)),
  ];
  assertNoFilenameClash(files, dialect);
  return files.map((file) => ({
    kind: CONTENT,
    filename: `${dialect}/migrations/${file.filename}`,
    contents: file.content,
  }));
}

function includedUpSqlByDialect(
  includedCustomMigrations: Record<string, IncludedPair[]>,
): Record<string, string[]> {
  const out: Record<string, string[]> = {};
  for (const [dialect, pairs] of Object.entries(includedCustomMigrations)) {
    out[dialect] = pairs.map((pair) => pair.up);
  }
  return out;
}

/** Shared datasource-objects step (catalog sort_order 1): fan `generateInitialMigration` over the settings-resolved SQL dialects into `<dialect>/migrations/`, appending each dialect's discovered custom migrations — both the local `custom/` folder and any carried in by datasource includes. Dialects come from `settings.backend.datasources` (default Sqlite); id type and table pluralization from `settings.datasource`. Generated as native `entries` so each carries its own `<dialect>/migrations/` path. */
export async function generate({
  inputs,
  settings,
}: SqlGenerateInput): Promise<GenerateEntry[]> {
  const project = structuredSettingsFromDict(settings);
  const {
    datasourceYamlText,
    datasourceSeedsYamlText,
    includedCustomMigrations,
  } = await inputs.all();
  const included = includedCustomMigrations ?? {};
  // parseDatasourceTypes yields DatasourceTypes; generate-sql consumes the same runtime object as SchemaData.
  const data = parseDatasourceTypes(
    datasourceYamlText,
    project,
    datasourceSeedsYamlText,
  ) as unknown as SchemaData;
  const dialects = resolveSchemaDialects({}, project);
  const ds = datasourceSettingsForSettings(project);
  const baseSqlOpts = {
    idType: ds.idType,
    withUuidColumn: ds.withUuidColumn,
    pluralizeTableNames: ds.pluralizeTableNames,
  };
  const migrationsByDialect: { dialect: string; chain: unknown }[] =
    dialects.map((lang: string) => ({
      dialect: normalizeDialect(lang)!,
      chain: generateInitialMigration(lang, data, baseSqlOpts),
    }));

  const coverageArgs = {
    datasourceData: data,
    deterministicDir: inputs.dir,
    dialects: migrationsByDialect.map((m) => m.dialect),
    extraCoverageSqlByDialect: includedUpSqlByDialect(included),
    useOptimisticConcurrency: ds.useOptimisticConcurrency,
  };
  await assertSkipMigrationsCovered(coverageArgs);

  const entries: GenerateEntry[] = [];
  for (const { dialect, chain } of migrationsByDialect) {
    entries.push(...chainMigrationEntries(dialect, chain));
    entries.push(
      ...(await customEntries(dialect, inputs.dir, included[dialect])),
    );
  }
  return entries;
}
