import {
  sized,
  charLen,
  numericFamily,
  requirePrecisionScale,
  DialectConverter,
  type Conversion,
  type DefaultsTable,
  type IdColumnSuffixes,
  type TriggerTable,
} from "./base.ts";

class OracleConverter extends DialectConverter {
  readonly target = "oracle";
  readonly conversions: Conversion[] = [
    {
      type: "string",
      native: sized("CLOB", (n) => `VARCHAR2(${n})`),
    },
    {
      type: "character",
      native: (f) => `CHAR(${charLen(f)})`,
    },
    ...numericFamily("NUMBER(10)", "NUMBER(5)", "NUMBER(19)"),
    { type: "unsignedinteger", native: "NUMBER(10)" },
    { type: "unsignedsmallinteger", native: "NUMBER(5)" },
    { type: "unsignedbiginteger", native: "NUMBER(20)" },
    { type: "float", native: "BINARY_DOUBLE" },
    {
      type: "decimal",
      native: (f) => {
        const [p, s] = requirePrecisionScale(f, "oracle");
        return `NUMBER(${p}, ${s})`;
      },
    },
    { type: "boolean", native: "NUMBER(1)" },
    { type: "datetime", native: "TIMESTAMP" },
    {
      type: "binary",
      native: sized("BLOB", (n) => `RAW(${n})`),
    },
    { type: "uuid", native: "VARCHAR2(36)" },
    { type: "reference", native: "NUMBER(10)" },
  ];
  readonly defaults: DefaultsTable = {
    Boolean: (v) => (v ? "1" : "0"),
    Now: () => `LOCALTIMESTAMP`,
    UtcNow: () => `SYS_EXTRACT_UTC(SYSTIMESTAMP)`,
    NewId: () => `SYS_GUID()`,
    Hex: (a) => `HEXTORAW('${a}')`,
  };
  readonly idColumn: IdColumnSuffixes = {
    integer: "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    biginteger: "NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    uuid: "VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY",
    string: "VARCHAR2(64) NOT NULL PRIMARY KEY",
  };
  readonly uuidColumn = "VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL UNIQUE";

  override dropTable(quoted: string): string {
    return `BEGIN EXECUTE IMMEDIATE 'DROP TABLE ${quoted} CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;\n/`;
  }

  updatedTrigger(table: TriggerTable): string {
    const { t, trg } = this.triggerNames(table);
    return `CREATE OR REPLACE TRIGGER ${trg}
BEFORE UPDATE ON ${t}
FOR EACH ROW
BEGIN
  :NEW.${this.quote("updated")} := ${this.defaults.UtcNow()};
END;
/`;
  }
}

export default new OracleConverter();
